### ISSUE TITLE
Advanced Search not showing up

### ISSUE THREAD

**Issue by sajidbsk** [SssWind/Waterlooworks-Azure#3]
When I click on Advanced Search or New Search, it seems to be giving me a blank website:
![image](https://user-images.githubusercontent.com/20984263/65342091-fea4b180-db9f-11e9-96ab-89350ddfa4d3.png)
![image](https://user-images.githubusercontent.com/20984263/65342109-095f4680-dba0-11e9-871f-c88fa201573a.png)

I have faced the same issue on Chrome and Firefox. When I open the console, this seems to be shown:
![image](https://user-images.githubusercontent.com/20984263/65342231-504d3c00-dba0-11e9-98b8-e6a52385feb5.png)

**Comment by SssWind** [comment]
Thanks for your feedback. I've uploaded V2.1.17 to the store. Since I don't have access to co-op postings this term, please let me know if there's still something wrong.
